interface ProjectScaffolderOptions {
  projectName: string;
  description: string;
  includeComponents?: boolean;
  includeTailwind?: boolean;
  includeShadcn?: boolean;
}

export class ProjectScaffolder {
  static generateProject(options: ProjectScaffolderOptions): Record<string, string> {
    const {
      projectName = "generated-project",
      description = "A React project generated by FikraHub",
      includeComponents = true,
      includeTailwind = true,
      includeShadcn = true
    } = options;

    const files: Record<string, string> = {};

    // Package.json with comprehensive dependencies
    files['package.json'] = JSON.stringify({
      "name": projectName.toLowerCase().replace(/\s+/g, '-'),
      "private": true,
      "version": "0.0.0",
      "type": "module",
      "description": description,
      "scripts": {
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
      },
      "dependencies": {
        "react": "^18.2.0",
        "react-dom": "^18.2.0",
        ...(includeShadcn && {
          "@radix-ui/react-slot": "^1.0.2",
          "@radix-ui/react-dialog": "^1.0.5",
          "@radix-ui/react-button": "^1.0.3",
          "class-variance-authority": "^0.7.0",
          "clsx": "^2.0.0",
          "tailwind-merge": "^2.0.0"
        }),
        ...(includeComponents && {
          "lucide-react": "^0.294.0"
        })
      },
      "devDependencies": {
        "@types/react": "^18.2.66",
        "@types/react-dom": "^18.2.22",
        "@vitejs/plugin-react": "^4.2.1",
        "vite": "^5.2.0",
        ...(includeTailwind && {
          "autoprefixer": "^10.4.19",
          "postcss": "^8.4.38",
          "tailwindcss": "^3.4.1"
        })
      }
    }, null, 2);

    // Vite config
    files['vite.config.js'] = `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
})`;

    // Tailwind config if enabled
    if (includeTailwind) {
      files['tailwind.config.js'] = `/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [],
}`;

      files['postcss.config.js'] = `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}`;
    }

    // CSS with design system variables
    files['src/index.css'] = `${includeTailwind ? '@import "tailwindcss/base";\n@import "tailwindcss/components";\n@import "tailwindcss/utilities";\n\n' : ''}@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 224 71.4% 4.1%;
    --card: 0 0% 100%;
    --card-foreground: 224 71.4% 4.1%;
    --popover: 0 0% 100%;
    --popover-foreground: 224 71.4% 4.1%;
    --primary: 220.9 39.3% 11%;
    --primary-foreground: 210 20% 98%;
    --secondary: 220 14.3% 95.9%;
    --secondary-foreground: 220.9 39.3% 11%;
    --muted: 220 14.3% 95.9%;
    --muted-foreground: 220 8.9% 46.1%;
    --accent: 220 14.3% 95.9%;
    --accent-foreground: 220.9 39.3% 11%;
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 210 20% 98%;
    --border: 220 13% 91%;
    --input: 220 13% 91%;
    --ring: 224 71.4% 4.1%;
    --radius: 0.5rem;
  }

  .dark {
    --background: 224 71.4% 4.1%;
    --foreground: 210 20% 98%;
    --card: 224 71.4% 4.1%;
    --card-foreground: 210 20% 98%;
    --popover: 224 71.4% 4.1%;
    --popover-foreground: 210 20% 98%;
    --primary: 210 20% 98%;
    --primary-foreground: 220.9 39.3% 11%;
    --secondary: 215 27.9% 16.9%;
    --secondary-foreground: 210 20% 98%;
    --muted: 215 27.9% 16.9%;
    --muted-foreground: 217.9 10.6% 64.9%;
    --accent: 215 27.9% 16.9%;
    --accent-foreground: 210 20% 98%;
    --destructive: 0 62.8% 30.6%;
    --destructive-foreground: 210 20% 98%;
    --border: 215 27.9% 16.9%;
    --input: 215 27.9% 16.9%;
    --ring: 216 12.2% 83.9%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}`;

    // Main entry point
    files['src/main.jsx'] = `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)`;

    // Generate intelligent App.jsx based on description
    files['src/App.jsx'] = this.generateAppComponent(description, includeComponents, includeShadcn);

    // Add shadcn utility functions if enabled
    if (includeShadcn) {
      files['src/lib/utils.js'] = `import { clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs) {
  return twMerge(clsx(inputs))
}`;

      // Add basic shadcn components
      files['src/components/ui/button.jsx'] = this.generateButtonComponent();
      files['src/components/ui/card.jsx'] = this.generateCardComponent();
    }

    // Basic HTML template
    files['index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" href="/vite.svg" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;

    // README file
    files['README.md'] = `# ${projectName}

${description}

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

Built with:
- React 18
- Vite
${includeTailwind ? '- Tailwind CSS' : ''}
${includeShadcn ? '- shadcn/ui components' : ''}

Generated by FikraHub Launch Mode.`;

    return files;
  }

  private static generateAppComponent(description: string, includeComponents: boolean, includeShadcn: boolean): string {
    const isLandingPage = description.toLowerCase().includes('landing') || description.toLowerCase().includes('homepage');
    const isDashboard = description.toLowerCase().includes('dashboard') || description.toLowerCase().includes('admin');
    const isEcommerce = description.toLowerCase().includes('shop') || description.toLowerCase().includes('store') || description.toLowerCase().includes('ecommerce');

    if (isLandingPage) {
      return this.generateLandingPageApp(includeComponents, includeShadcn);
    } else if (isDashboard) {
      return this.generateDashboardApp(includeComponents, includeShadcn);
    } else if (isEcommerce) {
      return this.generateEcommerceApp(includeComponents, includeShadcn);
    } else {
      return this.generateGenericApp(description, includeComponents, includeShadcn);
    }
  }

  private static generateLandingPageApp(includeComponents: boolean, includeShadcn: boolean): string {
    const imports = [];
    const components = [];

    if (includeComponents) imports.push('import { ArrowRight, CheckCircle, Star } from "lucide-react"');
    if (includeShadcn) imports.push('import { Button } from "./components/ui/button"', 'import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./components/ui/card"');

    return `import React from 'react'
${imports.join('\n')}

function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800">
      {/* Header */}
      <header className="container mx-auto px-4 py-6">
        <nav className="flex items-center justify-between">
          <div className="text-2xl font-bold text-gray-900 dark:text-white">
            YourBrand
          </div>
          <div className="hidden md:flex space-x-8">
            <a href="#features" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              Features
            </a>
            <a href="#pricing" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              Pricing
            </a>
            <a href="#contact" className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              Contact
            </a>
          </div>
          ${includeShadcn ? `<Button>Get Started</Button>` : `<button className="bg-indigo-600 hover:bg-indigo-700 text-white px-6 py-2 rounded-lg transition-colors">
            Get Started
          </button>`}
        </nav>
      </header>

      {/* Hero Section */}
      <section className="container mx-auto px-4 py-20 text-center">
        <h1 className="text-5xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6">
          Build Something
          <span className="text-indigo-600"> Amazing</span>
        </h1>
        <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
          Transform your ideas into reality with our powerful platform. 
          Start building today and see the difference.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          ${includeShadcn ? `<Button size="lg" className="bg-indigo-600 hover:bg-indigo-700">
            Start Free Trial ${includeComponents ? '<ArrowRight className="ml-2 h-5 w-5" />' : ''}
          </Button>
          <Button variant="outline" size="lg">
            Watch Demo
          </Button>` : `<button className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3 rounded-lg text-lg font-semibold transition-colors flex items-center justify-center">
            Start Free Trial ${includeComponents ? '<ArrowRight className="ml-2 h-5 w-5" />' : ''}
          </button>
          <button className="border border-gray-300 hover:border-gray-400 text-gray-700 dark:text-gray-300 px-8 py-3 rounded-lg text-lg font-semibold transition-colors">
            Watch Demo
          </button>`}
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 py-20">
        <h2 className="text-3xl font-bold text-center text-gray-900 dark:text-white mb-12">
          Why Choose Us?
        </h2>
        <div className="grid md:grid-cols-3 gap-8">
          ${[
            { title: 'Fast & Reliable', desc: 'Built for speed and performance that scales with your needs.' },
            { title: 'Easy to Use', desc: 'Intuitive interface that gets you up and running in minutes.' },
            { title: '24/7 Support', desc: 'Our team is here to help you succeed every step of the way.' }
          ].map((feature, index) => 
            includeShadcn ? `<Card key={${index}}>
            <CardHeader>
              <CardTitle className="flex items-center">
                ${includeComponents ? `<CheckCircle className="h-6 w-6 text-green-500 mr-2" />` : ''}
                ${feature.title}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                ${feature.desc}
              </CardDescription>
            </CardContent>
          </Card>` : `<div key={${index}} className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 flex items-center">
              ${includeComponents ? `<CheckCircle className="h-6 w-6 text-green-500 mr-2" />` : ''}
              ${feature.title}
            </h3>
            <p className="text-gray-600 dark:text-gray-300">
              ${feature.desc}
            </p>
          </div>`
          ).join('\n          ')}
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; 2024 YourBrand. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

export default App`;
  }

  private static generateDashboardApp(includeComponents: boolean, includeShadcn: boolean): string {
    return `import React, { useState } from 'react'
${includeComponents ? 'import { BarChart3, Users, DollarSign, Activity, Menu, Bell, Settings } from "lucide-react"' : ''}
${includeShadcn ? 'import { Button } from "./components/ui/button"\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./components/ui/card"' : ''}

function App() {
  const [sidebarOpen, setSidebarOpen] = useState(false)

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      {/* Sidebar */}
      <div className="{\`fixed inset-y-0 left-0 z-50 w-64 bg-white dark:bg-gray-800 shadow-lg transform transition-transform duration-300 ease-in-out \${sidebarOpen ? 'translate-x-0' : '-translate-x-full'} lg:translate-x-0\`}">
        <div className="flex items-center justify-center h-16 border-b border-gray-200 dark:border-gray-700">
          <h1 className="text-xl font-bold text-gray-900 dark:text-white">Dashboard</h1>
        </div>
        <nav className="mt-8">
          <div className="px-4 space-y-2">
            {['Overview', 'Analytics', 'Users', 'Settings'].map((item) => (
              <a key={item} href="#" className="block px-4 py-2 text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg">
                {item}
              </a>
            ))}
          </div>
        </nav>
      </div>

      {/* Main Content */}
      <div className="lg:ml-64">
        {/* Header */}
        <header className="bg-white dark:bg-gray-800 shadow-sm border-b border-gray-200 dark:border-gray-700">
          <div className="flex items-center justify-between px-6 py-4">
            <div className="flex items-center">
              ${includeComponents ? `<Button variant="ghost" size="sm" onClick={() => setSidebarOpen(!sidebarOpen)} className="lg:hidden">
                <Menu className="h-6 w-6" />
              </Button>` : `<button onClick={() => setSidebarOpen(!sidebarOpen)} className="lg:hidden p-2">
                <Menu className="h-6 w-6" />
              </button>`}
              <h2 className="ml-4 text-2xl font-semibold text-gray-900 dark:text-white">Overview</h2>
            </div>
            <div className="flex items-center space-x-4">
              ${includeComponents ? `<Button variant="ghost" size="sm">
                <Bell className="h-5 w-5" />
              </Button>
              <Button variant="ghost" size="sm">
                <Settings className="h-5 w-5" />
              </Button>` : `<button className="p-2">
                <Bell className="h-5 w-5" />
              </button>
              <button className="p-2">
                <Settings className="h-5 w-5" />
              </button>`}
            </div>
          </div>
        </header>

        {/* Dashboard Content */}
        <main className="p-6">
          {/* Stats Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
            ${[
              { title: 'Total Revenue', value: '$45,231.89', icon: 'DollarSign', change: '+20.1%' },
              { title: 'Active Users', value: '2,350', icon: 'Users', change: '+180.1%' },
              { title: 'Sales', value: '12,234', icon: 'BarChart3', change: '+19%' },
              { title: 'Active Now', value: '573', icon: 'Activity', change: '+201' }
            ].map((stat, index) => 
              includeShadcn ? `<Card key={${index}}>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  ${stat.title}
                </CardTitle>
                ${includeComponents ? `<${stat.icon} className="h-4 w-4 text-muted-foreground" />` : ''}
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">${stat.value}</div>
                <p className="text-xs text-muted-foreground">
                  ${stat.change} from last month
                </p>
              </CardContent>
            </Card>` : `<div key={${index}} className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
              <div className="flex items-center justify-between">
                <div>
                  <p className="text-sm font-medium text-gray-600 dark:text-gray-400">${stat.title}</p>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">${stat.value}</p>
                </div>
                ${includeComponents ? `<${stat.icon} className="h-8 w-8 text-gray-400" />` : ''}
              </div>
              <p className="text-xs text-gray-500 mt-2">${stat.change} from last month</p>
            </div>`
            ).join('\n            ')}
          </div>

          {/* Chart Area */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            ${includeShadcn ? `<Card className="col-span-1">
              <CardHeader>
                <CardTitle>Revenue Overview</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="h-[300px] bg-gray-100 dark:bg-gray-700 rounded flex items-center justify-center">
                  <p className="text-gray-500">Chart would go here</p>
                </div>
              </CardContent>
            </Card>
            <Card className="col-span-1">
              <CardHeader>
                <CardTitle>Recent Activity</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {['User John signed up', 'New order #1234', 'Payment received'].map((activity, index) => (
                    <div key={index} className="flex items-center space-x-4">
                      <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                      <p className="text-sm">{activity}</p>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>` : `<div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
              <h3 className="text-lg font-semibold mb-4">Revenue Overview</h3>
              <div className="h-[300px] bg-gray-100 dark:bg-gray-700 rounded flex items-center justify-center">
                <p className="text-gray-500">Chart would go here</p>
              </div>
            </div>
            <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow">
              <h3 className="text-lg font-semibold mb-4">Recent Activity</h3>
              <div className="space-y-4">
                {['User John signed up', 'New order #1234', 'Payment received'].map((activity, index) => (
                  <div key={index} className="flex items-center space-x-4">
                    <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
                    <p className="text-sm">{activity}</p>
                  </div>
                ))}
              </div>
            </div>`}
          </div>
        </main>
      </div>
    </div>
  )
}

export default App`;
  }

  private static generateEcommerceApp(includeComponents: boolean, includeShadcn: boolean): string {
    return `import React, { useState } from 'react'
${includeComponents ? 'import { Search, ShoppingCart, Heart, Star, Filter } from "lucide-react"' : ''}
${includeShadcn ? 'import { Button } from "./components/ui/button"\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./components/ui/card"' : ''}

function App() {
  const [cartCount, setCartCount] = useState(0)

  const products = [
    { id: 1, name: 'Premium Headphones', price: 299, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&h=300&fit=crop', rating: 4.5 },
    { id: 2, name: 'Wireless Mouse', price: 79, image: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&h=300&fit=crop', rating: 4.2 },
    { id: 3, name: 'Mechanical Keyboard', price: 159, image: 'https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=300&h=300&fit=crop', rating: 4.8 },
    { id: 4, name: 'USB-C Hub', price: 89, image: 'https://images.unsplash.com/photo-1625842268584-8f3296236761?w=300&h=300&fit=crop', rating: 4.3 }
  ]

  const addToCart = () => {
    setCartCount(prev => prev + 1)
  }

  return (
    <div className="min-h-screen bg-gray-50 dark:bg-gray-900">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 shadow-sm">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">TechStore</h1>
            
            {/* Search Bar */}
            <div className="flex-1 max-w-lg mx-8">
              <div className="relative">
                <input
                  type="text"
                  placeholder="Search products..."
                  className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:border-gray-600 dark:text-white"
                />
                ${includeComponents ? '<Search className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />' : ''}
              </div>
            </div>

            {/* Cart */}
            <div className="flex items-center space-x-4">
              ${includeShadcn ? `<Button variant="ghost" size="sm">
                ${includeComponents ? '<Heart className="h-5 w-5" />' : 'Wishlist'}
              </Button>
              <Button variant="ghost" size="sm" className="relative">
                ${includeComponents ? '<ShoppingCart className="h-5 w-5" />' : 'Cart'}
                {cartCount > 0 && (
                  <span className="absolute -top-2 -right-2 bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs">
                    {cartCount}
                  </span>
                )}
              </Button>` : `<button className="relative p-2">
                ${includeComponents ? '<ShoppingCart className="h-6 w-6" />' : 'Cart'}
                {cartCount > 0 && (
                  <span className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full w-5 h-5 flex items-center justify-center text-xs">
                    {cartCount}
                  </span>
                )}
              </button>`}
            </div>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="bg-gradient-to-r from-blue-600 to-purple-600 text-white py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            Latest Tech Products
          </h2>
          <p className="text-xl mb-8 opacity-90">
            Discover the best technology at unbeatable prices
          </p>
          ${includeShadcn ? `<Button size="lg" variant="secondary">
            Shop Now
          </Button>` : `<button className="bg-white text-blue-600 px-8 py-3 rounded-lg font-semibold text-lg hover:bg-gray-100 transition-colors">
            Shop Now
          </button>`}
        </div>
      </section>

      {/* Filters */}
      <section className="container mx-auto px-4 py-8">
        <div className="flex items-center justify-between mb-8">
          <h3 className="text-2xl font-bold text-gray-900 dark:text-white">Products</h3>
          ${includeShadcn ? `<Button variant="outline">
            ${includeComponents ? '<Filter className="h-4 w-4 mr-2" />' : ''}
            Filters
          </Button>` : `<button className="flex items-center px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50">
            ${includeComponents ? '<Filter className="h-4 w-4 mr-2" />' : ''}
            Filters
          </button>`}
        </div>

        {/* Products Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {products.map((product) => (
            ${includeShadcn ? `<Card key={product.id} className="group hover:shadow-lg transition-shadow">
              <div className="aspect-square overflow-hidden rounded-t-lg">
                <img
                  src={product.image}
                  alt={product.name}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                />
              </div>
              <CardHeader>
                <CardTitle className="text-lg">{product.name}</CardTitle>
                <div className="flex items-center space-x-1">
                  {[...Array(5)].map((_, i) => (
                    <Star
                      key={i}
                      className={\`h-4 w-4 \${i < Math.floor(product.rating) ? 'text-yellow-400 fill-current' : 'text-gray-300'}\`}
                    />
                  ))}
                  <span className="text-sm text-gray-600">({product.rating})</span>
                </div>
              </CardHeader>
              <CardContent>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold text-gray-900 dark:text-white">
                    \${product.price}
                  </span>
                  <Button onClick={addToCart} size="sm">
                    Add to Cart
                  </Button>
                </div>
              </CardContent>
            </Card>` : `<div key={product.id} className="bg-white dark:bg-gray-800 rounded-lg shadow-md hover:shadow-lg transition-shadow group">
              <div className="aspect-square overflow-hidden rounded-t-lg">
                <img
                  src={product.image}
                  alt={product.name}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                />
              </div>
              <div className="p-4">
                <h4 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">{product.name}</h4>
                <div className="flex items-center space-x-1 mb-3">
                  {[...Array(5)].map((_, i) => (
                    <Star
                      key={i}
                      className={\`h-4 w-4 \${i < Math.floor(product.rating) ? 'text-yellow-400 fill-current' : 'text-gray-300'}\`}
                    />
                  ))}
                  <span className="text-sm text-gray-600">({product.rating})</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold text-gray-900 dark:text-white">
                    \${product.price}
                  </span>
                  <button
                    onClick={addToCart}
                    className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition-colors"
                  >
                    Add to Cart
                  </button>
                </div>
              </div>
            </div>`}
          ))}
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-white py-12 mt-16">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; 2024 TechStore. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

export default App`;
  }

  private static generateGenericApp(description: string, includeComponents: boolean, includeShadcn: boolean): string {
    return `import React from 'react'
${includeComponents ? 'import { Sparkles, ArrowRight } from "lucide-react"' : ''}
${includeShadcn ? 'import { Button } from "./components/ui/button"\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from "./components/ui/card"' : ''}

function App() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800">
      <div className="container mx-auto px-4 py-16">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 dark:text-white mb-6">
            ${includeComponents ? '<Sparkles className="inline-block mr-3 h-12 w-12 text-indigo-600" />' : ''}
            Welcome to Your App
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8 max-w-2xl mx-auto">
            ${description}
          </p>
          ${includeShadcn ? `<Button size="lg" className="bg-indigo-600 hover:bg-indigo-700">
            Get Started ${includeComponents ? '<ArrowRight className="ml-2 h-5 w-5" />' : ''}
          </Button>` : `<button className="bg-indigo-600 hover:bg-indigo-700 text-white px-8 py-3 rounded-lg text-lg font-semibold transition-colors flex items-center justify-center mx-auto">
            Get Started ${includeComponents ? '<ArrowRight className="ml-2 h-5 w-5" />' : ''}
          </button>`}
        </div>

        <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
          ${[
            { title: 'Feature One', desc: 'Describe your first amazing feature here.' },
            { title: 'Feature Two', desc: 'Explain another great capability of your app.' },
            { title: 'Feature Three', desc: 'Highlight what makes your solution unique.' }
          ].map((feature, index) => 
            includeShadcn ? `<Card key={${index}}>
            <CardHeader>
              <CardTitle>{feature.title}</CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                {feature.desc}
              </CardDescription>
            </CardContent>
          </Card>` : `<div key={${index}} className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg">
            <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">
              {feature.title}
            </h3>
            <p className="text-gray-600 dark:text-gray-300">
              {feature.desc}
            </p>
          </div>`
          ).join('\n          ')}
        </div>
      </div>
    </div>
  )
}

export default App`;
  }

  private static generateButtonComponent(): string {
    return `import React from "react"
import { cva } from "class-variance-authority"
import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive: "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline: "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

const Button = React.forwardRef(({ className, variant, size, ...props }, ref) => {
  return (
    <button
      className={cn(buttonVariants({ variant, size, className }))}
      ref={ref}
      {...props}
    />
  )
})
Button.displayName = "Button"

export { Button, buttonVariants }`;
  }

  private static generateCardComponent(): string {
    return `import React from "react"
import { cn } from "@/lib/utils"

const Card = React.forwardRef(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)}
    {...props}
  />
))
Card.displayName = "Card"

const CardHeader = React.forwardRef(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
))
CardHeader.displayName = "CardHeader"

const CardTitle = React.forwardRef(({ className, ...props }, ref) => (
  <h3
    ref={ref}
    className={cn("text-2xl font-semibold leading-none tracking-tight", className)}
    {...props}
  />
))
CardTitle.displayName = "CardTitle"

const CardDescription = React.forwardRef(({ className, ...props }, ref) => (
  <p ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
))
CardDescription.displayName = "CardDescription"

const CardContent = React.forwardRef(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
))
CardContent.displayName = "CardContent"

const CardFooter = React.forwardRef(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
))
CardFooter.displayName = "CardFooter"

export { Card, CardHeader, CardFooter, CardTitle, CardDescription, CardContent }`;
  }
}