export enum QueryKeysEnum {
  GET_ME = 'GET_ME',
  GET_USER_COUNT = 'GET_USER_COUNT',
  GET_USERS = 'GET_USERS',
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID',
  GET_ROLES = 'GET_ROLES',
  GET_ROLE_BY_ID = 'GET_ROLE_BY_ID',
  GET_SPECIALTIES = 'GET_SPECIALTIES',
  GET_SPECIALTY_BY_ID = 'GET_SPECIALTY_BY_ID',
  GET_USER_BY_ID = 'GET_USER_BY_ID',
}
